name: flutterapp

description: A new Flutter project.

version: 1.0.0


# The environment SDK constraint
environment:
  sdk: "^3.7.2"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  shared_preferences: ^2.0.0
  webview_flutter_android: ^4.3.4 # Use the latest version
  webview_flutter: ^4.0.0
  intl_phone_field: ^3.1.0
  package_info_plus: ^4.0.0
  flutter_launcher_icons: ^0.14.4 


dev_dependencies:
  flutter_test:
    sdk: flutter # Make sure to use the latest version available
  flutter_lints: ^3.0.0

flutter_icons:
    image_path: "images/Logo-Sq.png"
    android: true 
    ios: true 
  


flutter:
  uses-material-design: true
  assets:
  - images/




    
 